### ISSUE TITLE
关于Linux系统部署报错问题

### ISSUE THREAD

**Issue by immarktube** [DIYgod/GoodNight#8]
你好，我今天尝试在服务器上部署，一切就绪后成功过一次，心跳跳了3次，然后就停了。回到家后我重启了服务器继续启动就报错。

```
(node:1659) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: 1101 == 0
    at Object.equal (/usr/local/GoodNight/node_modules/wechat4u/lib/util/global.js:69:24)
    at /usr/local/GoodNight/node_modules/wechat4u/lib/core.js:187:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
我已经不止一次看到这个错误了。

**Comment by immarktube** [comment]
```
[root@iz2zednj5dqundk0437u2dz GoodNight]# node -v
v10.15.0
[root@iz2zednj5dqundk0437u2dz GoodNight]# npm -v
6.4.1
```

**Comment by immarktube** [comment]
大家都散了吧，the owner已经不维护此项目了。
